Parameters:
  ClusterName:
    Description: Cluster name
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  KubCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref ClusterName
      Version: '1.17'
      RoleArn: !GetAtt eksClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: 
              !Sub "${EnvironmentName}-SecGrp"
        SubnetIds:
          - Fn::ImportValue: 
              !Sub "${EnvironmentName}-PUB1-SN"
          - Fn::ImportValue: 
              !Sub "${EnvironmentName}-PUB2-SN"
