apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: container-deploy
          image: almaha96/capstone:latest
          ports:
            - containerPort: 80
